spring:
    datasource:
        name: data1
        url: jdbc:mysql://localhost:3307/data1
        username: mysql
        password: mysql

server.port=8082
server.session.timeout=10
server.tomcat.max-threads=800
server.tomcat.uri-encoding=UTF-8
# MVC  分版本
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp